version: "2"

services:
  namenode:
    image: hadoop-name
    volumes:
      - namenode:/hadoop/dfs/name
    depends_on:
      - datanode
      - hive-server
      - hive-metastore
      - hive-metastore-postgresql
    ports:
      - "50070:50070"
  datanode:
    image: hadoop-data
    volumes:
      - datanode:/hadoop/dfs/data
    ports:
      - "50075:50075"
  hive-server:
    image: hadoop-hive
    ports:
      - "10000:10000"
  hive-metastore:
    image: hadoop-hive
    command: /opt/hive/bin/hive --service metastore
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    image: hadoop-hive

volumes:
  namenode:
  datanode:
