version: "3" 

services:
  namenode:
    image: m1c4lv/hadoop-namenode:debian11
    container_name: namenode
    restart: always
    volumes:
      - namenode:/opt/volume/namenode
    ports:
      - "9870:9870"
  datanode:
    image: m1c4lv/hadoop-datanode:debian11
    container_name: datanode
    restart: always
    depends_on:
      - namenode
    volumes:
      - datanode:/opt/volume/datanode
  datanode1:
    image: m1c4lv/hadoop-datanode:debian11
    container_name: datanode1
    restart: always
    depends_on:
      - namenode
    volumes:
      - datanode1:/opt/volume/datanode
  datanode2:
    image: m1c4lv/hadoop-datanode:debian11
    container_name: datanode2
    restart: always
    depends_on:
      - namenode
    volumes:
      - datanode2:/opt/volume/datanode
  resourcemanager:
    image: m1c4lv/hadoop-resourcemanager:debian11
    container_name: resourcemanager
    restart: always
    depends_on:
      - namenode
    ports:
      - "8088:8088"
  nodemanager:
    image: m1c4lv/hadoop-nodemanager:debian11
    container_name: nodemanager
    restart: always
    depends_on:
      - namenode
    ports:
      - "8042:8042"
  historyserver:
    image: m1c4lv/hadoop-historyserver:debian11
    container_name: historyserver
    restart: always
    volumes:
      - historyserver:/hadoop/yarn/timeline
    depends_on:
      - namenode
  hive-server:
    image: m1c4lv/hadoop-hive:debian11
    container_name: hiveserver
    command: /bin/sh -c '/usr/local/bin/script_schematool.sh && /usr/local/bin/script_hive.sh'
    restart: always
    depends_on:
      - namenode
    ports:
      - "10000:10000"
      - "10002:10002"
  mysql-server:
    image: mysql:5.7-debian
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql-server:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "33306:3306"
  jupyter:
    image: m1c4lv/hadoop-jupyter:debian11
    container_name: jupyter
    command: /opt/anaconda/bin/jupyter notebook --ip='*' --port=8888 --notebook-dir=/opt/notebooks --no-browser --allow-root
    restart: always
    volumes:
      - jupyter:/opt/notebooks
    ports:
      - "8888:8888"

volumes:
  namenode:
  datanode:
  datanode1:
  datanode2:
  historyserver:
  mysql-server:
  jupyter:
