kind: Service
apiVersion: v1
metadata:
  name: namenode
spec:
  selector:
    app: namenode
  ports:
    - port: 9870
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-namenode
spec:
  selector:
    matchLabels:
      app: namenode # has to match .spec.template.metadata.labels
  serviceName: "namenode"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: namenode # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: namenode
        image: m1c4lv/hadoop-namenode:debian11
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        ports:
        - containerPort: 9870
          name: namenode
        volumeMounts:
        - name: namenode
          mountPath: /opt/volume/namenode
  volumeClaimTemplates:
  - metadata:
      name: namenode
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
