kind: Service
apiVersion: v1
metadata:
  name: nodemanager
spec:
  selector:
    app: nodemanager
  ports:
    - port: 8042
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodemanager
  labels:
    app: nodemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodemanager
  template:
    metadata:
      labels:
        app: nodemanager
    spec:
      containers:
      - name: nodemanager
        image: m1c4lv/hadoop-nodemanager:debian11
        ports:
        - containerPort: 8042
