kind: Service
apiVersion: v1
metadata:
  name: resourcemanager
spec:
  selector:
    app: resourcemanager
  ports:
    - port: 8088
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcemanager
  labels:
    app: resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourcemanager
  template:
    metadata:
      labels:
        app: resourcemanager
    spec:
      containers:
      - name: resourcemanager
        image: m1c4lv/hadoop-resourcemanager:debian11
        command: ["sh", "-c", sleep 100 && $HADOOP_HOME/bin/yarn resourcemanager]
        ports:
        - containerPort: 8088
